export const IMAGE_CONFIG = {
    ZOOM_FACTOR: 2,
    LENS_SIZE: 100,
    MAIN_IMAGE_WIDTH: 444,
    MAIN_IMAGE_HEIGHT: 530,
    ZOOMED_IMAGE_WIDTH: 444,
    ZOOMED_IMAGE_HEIGHT: 530,
    THUMBNAIL_WIDTH: 152,
    THUMBNAIL_HEIGHT: 167,
    THUMBNAIL_MAIN_WIDTH: 80,
    THUMBNAIL_MAIN_HEIGHT: 80,
} as const;